[package]
name = "list13-24"
version = "0.1.0"
authors = ["Meng <sunmeng90@126.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
